# This file allows testing your addon using travis CI servers to use it you'll need to
# create an account in travis.org and enable your addon there.
#
# By default it will test linux 64bit and osx against the master and stable OF branches.
# Other platforms can be enabled by uncommenting the corresponding sections.
#
# If any extra install is needed to use the addon it can be included in the corresponding
# install script in:
#
# scripts/ci/$TARGET/install.sh
#


language: c++
compiler: gcc
sudo: true
matrix:
  include:
  # fully specify builds, include can't dynamically expand matrix entries
  # relative order of sudo and env is important so that addons: is recognized

# Linux 64bit, OF master
  - os: linux
    dist: trusty
    sudo: required
    env: TARGET="linux64" OF_BRANCH="master"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
          - g++-4.9
          - gdb

# Linux 64bit, OF stable:  Not supported yet
#  - os: linux
#    dist: trusty
#    sudo: required
#    env: TARGET="linux64" OF_BRANCH="stable"
#    addons:
#      apt:
#        sources:
#          - ubuntu-toolchain-r-test
#        packages:
#          - gcc-4.9
#          - g++-4.9
#          - gdb

# OSX, OF master
#  - os: osx
#    osx_image: xcode8
#    compiler: clang
#    env: TARGET="osx" OF_BRANCH="master"

# OSX, OF stable:  Not supported yet
#  - os: osx
#    osx_image: xcode8
#    compiler: clang
#    env: TARGET="osx" OF_BRANCH="stable"

# Linux ARM6, OF master: Uncomment following lines to enable
#  - os: linux
#    sudo: required
#    dist: trusty
#    env: TARGET="linuxarmv6l" OF_BRANCH="master"


# Linux ARM6, OF stable:  Not supported yet
#  - os: linux
#    sudo: required
#    dist: trusty
#    env: TARGET="linuxarmv6l" OF_BRANCH="stable"

# Linux ARM7, OF master: Uncomment following lines to enable
#  - os: linux
#    sudo: false
#    env: TARGET="linuxarmv7l" OF_BRANCH="master"
#    cache:
#      directories:
#        - ~/rpi2_toolchain
#        - ~/firmware-master
#        - ~/archlinux

# Linux ARM7, OF stable:  Not supported yet
#  - os: linux
#    sudo: false
#    env: TARGET="linuxarmv7l" OF_BRANCH="stable"
#    cache:
#      directories:
#        - ~/rpi2_toolchain
#        - ~/firmware-master
#        - ~/archlinux


# Emscripten, OF master: Uncomment following lines to enable
#  - os: linux
#    sudo: false
#    env: TARGET="emscripten" OF_BRANCH="master"
#    addons:
#      apt:
#        sources:
#          - ubuntu-toolchain-r-test
#        packages:
#          - libstdc++6


# Emscripten, OF stable: Not supported yet
#  - os: linux
#    sudo: false
#    env: TARGET="emscripten" OF_BRANCH="stable"
#    addons:
#      apt:
#        sources:
#          - ubuntu-toolchain-r-test
#        packages:
#          - libstdc++6


# Android armv7, OF master: Uncomment following lines to enable
#  - os: linux
#    sudo: false
#    env: TARGET="android" OPT="armv7" OF_BRANCH="master"
#    cache:
#      directories:
#        - ~/android-ndk-r12b


# Android armv7, OF stable: Not supported yet
#  - os: linux
#    sudo: false
#    env: TARGET="android" OPT="armv7" OF_BRANCH="stable"
#    cache:
#      directories:
#        - ~/android-ndk-r12b


# Android x86, OF master: Uncomment following lines to enable
#  - os: linux
#    sudo: false
#    env: TARGET="android" OPT="x86" OF_BRANCH="master"
#    cache:
#      directories:
#        - ~/android-ndk-r12b


# Android x86, OF stable: Not supported yet
#  - os: linux
#    sudo: false
#    env: TARGET="android" OPT="x86" OF_BRANCH="stable"
#    cache:
#      directories:
#        - ~/android-ndk-r12b


  # Exclude the default build that would otherwise be generated
  # see https://github.com/travis-ci/travis-ci/issues/1228
  exclude:
    - compiler: gcc

install:
  - cd ~
  - git clone --depth=1 --branch=$OF_BRANCH https://github.com/openframeworks/openFrameworks
  - cd openFrameworks
  - git clone --branch=master https://github.com/d3cod3/ofxAudioAnalyzer addons/ofxAudioAnalyzer
  - git clone --branch=master https://github.com/npisanti/ofxAudioFile addons/ofxAudioFile
  - git clone --branch=master https://github.com/d3cod3/ofxBTrack addons/ofxBTrack
  - git clone --branch=master https://github.com/d3cod3/ofxChromaKeyShader addons/ofxChromaKeyShader
  - git clone --branch=master https://github.com/kylemcdonald/ofxCv addons/ofxCv
  - git clone --branch=master https://github.com/d3cod3/ofxDatGui addons/ofxDatGui
  - git clone --branch=master https://github.com/d3cod3/ofxFontStash addons/ofxFontStash
  - git clone --branch=master https://github.com/d3cod3/ofxGLEditor addons/ofxGLEditor
  - git clone --branch=master https://github.com/armadillu/ofxGLError addons/ofxGLError
  - git clone --branch=master https://github.com/armadillu/ofxHistoryPlot addons/ofxHistoryPlot
  - git clone --branch=master https://github.com/d3cod3/ofxInfiniteCanvas addons/ofxInfiniteCanvas
  - git clone --branch=of-0.10.0 https://github.com/d3cod3/ofxLua addons/ofxLua
  - git clone --branch=master https://github.com/d3cod3/ofxMidi addons/ofxMidi
  - git clone --branch=master https://github.com/d3cod3/ofxParagraph addons/ofxParagraph
  - git clone --branch=master https://github.com/npisanti/ofxPDSP addons/ofxPDSP
  - git clone --branch=OF0.9.8 https://github.com/d3cod3/ofxPython addons/ofxPython
  - git clone --branch=master https://github.com/d3cod3/ofxSIMDFloats addons/ofxSIMDFloats
  - git clone --branch=master https://github.com/d3cod3/ofxTimeline addons/ofxTimeline
  - git clone --branch=master https://github.com/armadillu/ofxTimeMeasurements addons/ofxTimeMeasurements
  - scripts/ci/addons/install.sh
  - cd ~
  - curl -SLsO https://raw.githubusercontent.com/d3cod3/ofxVisualProgramming/scripts/ci/addons/install.sh
  - chmod +x install.sh

before_script:
  - cd ~
  - git clone --branch=master https://github.com/d3cod3/fftw3.3.2-source
  - cd fftw3.3.2-source
  - ./configure --prefix=`pwd` --enable-float --enable-sse2 --with-incoming-stack-boundary=2 --with-our-malloc16 --disable-shared --enable-static
  - make
  - cd .libs
  - cp libfftw3f.a ~/openFrameworks/addons/ofxAudioAnalyzer/libs/fftw3f/lib/$TARGET/
  - cd ~/openFrameworks

script:
  - if [ "$TARGET" = "linux64" ]; then scripts/ci/addons/build.sh > /dev/null; else scripts/ci/addons/build.sh; fi

git:
  depth: 10
